In [1]:
import numpy as np
import tensorflow as tf

C:\Users\sumas\Anaconda3\lib\site-packages\h5py\__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [4]:
no_of_inputs = 3
no_of_neurons = 5

x0 = tf.placeholder(tf.float32, [None, no_of_inputs])
x1 = tf.placeholder(tf.float32, [None, no_of_inputs])

#tf.Variable represents a tensor whose value can be changed by running ops on it. Stores persistent tensor
wx = tf.Variable(tf.random_normal(shape=[no_of_inputs, no_of_neurons], dtype = tf.float32))
wy = tf.Variable(tf.random_normal(shape=[no_of_neurons, no_of_neurons], dtype = tf.float32))
bias = tf.Variable(tf.zeros([1, no_of_neurons], dtype = tf.float32))

y0 = tf.tanh(tf.matmul(x0,wx)+bias)
y1 = tf.tanh(tf.matmul(y0,wy) + tf.matmul(x1,wx)+bias)

init = tf.global_variables_initializer()

In [5]:
X0_batch = np.array([[0,1,2],[3,4,5],[6,7,8],[9,0,1]]) # t=0
X1_batch = np.array([[9,8,7],[0,0,0],[6,5,4],[3,2,1]])

In [6]:
with tf.Session() as sess:
    init.run()
    y0_val, y1_val = sess.run([y0,y1], feed_dict={x0:X0_batch, x1:X1_batch})

In [7]:
print(y0_val)

[[-0.9938276  -0.22139739  0.3100919  -0.9997919  -0.43286067]
 [-0.99999976 -0.98123217  0.9650564  -1.         -0.96166456]
 [-1.         -0.9997185   0.9987997  -1.         -0.9980721 ]
 [ 0.95164174 -0.9999852  -0.96563226 -0.9999338  -0.9999993 ]]


In [8]:
print(y1_val)

[[-1.         -0.9999907   0.99995166 -1.         -0.95512754]
 [-0.9926963  -0.41656077  0.26434013 -0.99890566  0.9931155 ]
 [-1.         -0.99972725  0.99750805 -1.          0.3063197 ]
 [-0.9923136   0.02557137  0.13982907 -0.9746943  -0.95565957]]
